Repository VirtoCommerce/vc-storefront, pull requests merged in 2019-12, with the labels that each got.

#353 disllow log in under the other store account
  VirtoCommerce.Storefront/Controllers/AccountController.cs
Labels: bug

#355 Update Dependencies
  VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj
  VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj
  VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj
  VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Labels: dependencies, renovate

#357 Update Dependencies
  VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj
  VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj
  VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj
Labels: dependencies, renovate

#359 Update Dependencies to v2.12.0
  VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Labels: dependencies, renovate

#364 Ignore ARR Affinity Cookie
  VirtoCommerce.Storefront/DependencyInjection/ServiceCollectionExtension.cs
Labels: bug, client request

#365 Update dependency FluentValidation to v8.6.1
  VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj
Labels: dependencies, renovate
